### ISSUE TITLE
Ensure output of Template 1A has 1 row per patient

### ISSUE THREAD

**Issue by justaddcoffee** [National-Clinical-Cohort-Collaborative/n3c_machine_learning#1]

**Comment by bryanlaraway** [comment]
Added a SQL node to the final COVID_Patient_Summary_Table entitled one_row_per_patient_validation with a simple SQL statement, confirms (currently) that there is only one row per patient:

`select count(*) as duplicate_count from 
(SELECT person_id
FROM COVID_Patient_Summary_Table
group by person_id 
having count(person_id) > 1
)`

**Comment by justaddcoffee** [comment]
Thanks @bryanlaraway!
